# ------------------------------------------------------ #
# Tip: sort properties alphabetically. Even nested ones! #
# Tip: all property keys lowercase!!!                    #
# ------------------------------------------------------ #
# Entities root packages
entities:
    package: 'com.minecade.rfb.data'

# Server
server:
    announcements:
    - '&dVisit http://skydoesminecraft.com/shop to purchase VIP!'
    - '&dJoin the fun at http://skydoesminecraft.com for up-to-date information on Sky Networks!'
    - '&dVIP users can join to full servers, visit http://skydoesminecraft.com/shop to purchase VIP!'
    - '&dWant to be the Beast? Get VIP at http://skydoesminecraft.com/shop'
    id: <index>     
    name: 'Run from The Beast Server <index>'

# Match
match:
    ban-message: 'You have been banned from sky servers. Appeal at http://skydoesminecraft.com/'
    lobby-world-name: 'RFBLobbyWorld'
    time: 300 # Match duration time in seconds.
    start-countdown: 20 # The time in seconds to wait when the MATCH_PLAYERS limit reached to start the match.
    ready-countdown: 15 # The time to wait until all runners are ready to start to run.
    beast-countdown: 15 # The time to wait until get free the beast.
    required-players: 6 # Minimun Players needed to start the match.
    server-full-message: 'The server if full, visit skydoesminecraft.com/shop to purchase VIP!'

# Lobby
lobby:
    spawn:
        x: -5
        y: 49
        z: 2
        pitch: 0
        yaw: 90
        world: RFBLobbyWorld

# Central Database
minecade:
    central-database:
        username: runbeast
        driver: com.mysql.jdbc.Driver
        password: hrg2mTGy2JAh
        url: jdbc:mysql://172.23.24.95:3306/sky_network
